Cargar Numpy

In [1]:
import numpy as np

LO BÁSICO

In [ ]:
ARREGLOS

In [2]:
a = np.array([11,21,31], dtype='int32')
print(a)

[11 21 31]


In [3]:
b = np.array([[91.0,81.0,71.0],[61.0,51.0,41.0]])
print(b)

[[91. 81. 71.]
 [61. 51. 41.]]


In [4]:
# OBTENER LA  Dimension
a.ndim

1

In [5]:
# Get Dimension
b.ndim

2

In [6]:
# Obtener el  Tipo
a.dtype

dtype('int32')

In [9]:
b.dtype

dtype('float64')

In [7]:
# obtener el tamaño
a.itemsize


4

In [8]:
b.itemsize

8

In [10]:
#Obtener el tamaño total en bytes que ocupa un array.
a.nbytes

12

In [11]:
b.nbytes

48

Acceder a las filas, columnas y cambiarlas

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
# Obtener un elemtodel arreglo [filas, columnas]
#los arreglos inician en cero
a[1, 5]

13

In [15]:
# Obtener una fila en particular
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# Obtener una columna en particular
a[:, 4]

array([ 5, 12])

In [21]:
# Obtener [inicioindex:efinindex:salto]
a[0, 1:-2:2]

array([2, 4])

In [24]:
a[1,5] = 30

a[:,2] = [11,22]
print(a)

[[ 1  2 11  4  5  6  7]
 [ 8  9 22 11 12 30 14]]


Ejemplo en 3 dimensiones

In [53]:
b = np.array([[[11,22],[33,44]],[[55,66],[77,88]]])
print(b)

[[[11 22]
  [33 44]]

 [[55 66]
  [77 88]]]


In [57]:
# fila, columna, profundidad
b[1,0,0] 

55

In [44]:
b.ndim

3

In [37]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [38]:
b

array([[[11, 22],
        [ 9,  9]],

       [[55, 66],
        [ 8,  8]]])

Diferentes tipos de arreglos

In [58]:
np.ones((4,2,3), dtype='int32')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [59]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [60]:
# el arreglo con 19
np.full((2,2), 19)

array([[19, 19],
       [19, 19]])

In [61]:
a

array([[ 1,  2, 11,  4,  5,  6,  7],
       [ 8,  9, 22, 11, 12, 30, 14]])

In [62]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [63]:
np.random.rand(4,2)

array([[0.11918225, 0.63263855],
       [0.81326634, 0.73887592],
       [0.52789839, 0.73634242],
       [0.46478625, 0.34646636]])

In [64]:

np.random.randint(-5,8, size=(2,3))

array([[ 6, -3, -3],
       [ 6,  2,  6]])

In [65]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [66]:
#repetir un arrelglo
arreglo = np.array([[1,2,3]])

In [67]:
arreglo

array([[1, 2, 3]])

In [68]:
r1 = np.repeat(arreglo,3, axis=0)

In [69]:
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [70]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


copiar arreglos

In [72]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


MATEMATICAS

In [73]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [74]:
a + 2

array([3, 4, 5, 6])

In [75]:
a - 2

array([-1,  0,  1,  2])

In [76]:
a * 2

array([2, 4, 6, 8])

In [77]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [79]:
a

array([1, 2, 3, 4])

In [78]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [80]:
a ** 2

array([ 1,  4,  9, 16])

In [81]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

https://numpy.org/doc/1.18/reference/routines.math.html

ALGEBRA LINEAL

In [82]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)
# Producto matricial de dos matrices.
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [83]:
c = np.identity(3)

In [84]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
#determinante
np.linalg.det(c)

1.0

https://www.tutorialspoint.com/numpy/numpy_determinant.htm

In [ ]:

# Trace
#Devuelve la suma a lo largo de las diagonales de la matriz.


In [86]:
np.trace(np.eye(3))


3.0

In [89]:
a = np.arange(8).reshape((2,2,2))
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [90]:
np.trace(a)

array([6, 8])

 Singular Vector Decomposition
https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html

Eigenvalues
Calcule los valores propios y los vectores propios derechos de una matriz cuadrada.
https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html

 Matrix Norm
 https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html#:~:text=Matrix%20or%20vector%20norm.,value%20of%20the%20ord%20parameter.&text=Input%20array.,D%2C%20unless%20ord%20is%20None.

Inverse
https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html


ESTADISTICA



In [91]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
np.min(stats)

1

In [93]:
np.max(stats, axis=1)

array([3, 6])

In [94]:
np.sum(stats, axis=0)

array([5, 7, 9])

ORGANIZAR ARREGLOS

In [95]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [96]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])